[versions]
agp = "8.13.2"
androidx-activity-compose = "1.12.2"
appcompat = "1.7.1"
compile-sdk-version = "36"
compose-bom = "2025.12.01"
core-ktx = "1.17.0"
detekt = "1.23.8"
espresso-core = "3.7.0"
junit = "4.13.2"
kotlin = "2.3.0"
min-sdk-version = "23"
nexus-publish = "2.0.0"
target-sdk-version = "36"
media3 = "1.5.1"

[libraries]
# Peças do Sistema e Teste Geral
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version = "1.3.0" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.7.0" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.7.0" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }

# AS PEÇAS DO COMPOSE TEST (O que resolve o erro atual)
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

# Motor do Monstro e Interface
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material = { module = "androidx.compose.material:material" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
