name: Monstro V18 - Build Turbo (Cache ON)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  gradle:
    name: Gerar APK em 50s
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Gradle (Colecionando Cache)
        uses: gradle/actions/setup-gradle@v4
        with:
          # Mudei para FALSE: Agora ele guarda e usa o cache saudável
          cache-disabled: false
          cache-cleanup: on-success

      - name: Compilar APK Monstro
        # Sem o 'build' inútil, apenas o APK direto
        run: ./gradlew assembleDebug

      - name: Upload APK do Monstro
        uses: actions/upload-artifact@v4
        with:
          name: Monstro-V18-APK
          path: app/build/outputs/apk/debug/app-debug.apk
