name: Monstro V18 - Build Limpo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  gradle:
    name: Gerar APK Sem Sujeira
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Gradle (Reset Total)
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true # Garante que nada do cache antigo quebre o build
          cache-cleanup: always

      - name: Compilar APK Monstro
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK Final
        uses: actions/upload-artifact@v4
        with:
          name: Monstro-V18-APK
          path: app/build/outputs/apk/debug/app-debug.apk
